In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os
from pprint import pp
from que_onda import *
import random
import tensorflow as tf

np.set_printoptions(floatmode='unique')
dtype = tf.float32
n_levels = 10
wavelet_name = 'sym6'

wavelet = wavelets.by_name(wavelet_name, dtype)
filters = wavelets.dwt_filters(wavelet)


2025-04-24 15:07:33.541807: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
files = os.walk('data')
# files = [
#          ('data/mp3/MedleyDB_V1', [], [
#                                    'AlexanderRoss_VelvetCurtain_MIX.mp3',
#                                    'CelestialShore_DieForUs_MIX.mp3',
#                                    'ClaraBerryAndWooldog_TheBadGuys_MIX.mp3',
#                                    'ClaraBerryAndWooldog_WaltzForMyVictims_MIX.mp3',
#                                    'Debussy_LenfantProdigue_MIX.mp3',
#                                    'EthanHein_BluesForNofi_MIX.mp3'
#                                    ]),
#          ('data/mp3/MedleyDB_V2', [], [
#                                    'Allegria_MendelssohnMovement1_MIX.mp3',
#                                    'BarefootSisters_RedJetta_MIX.mp3',
#                                    'CatMartino_IPromise_MIX.mp3',
#                                    'Cayetana_MissThing_MIX.mp3',
#                                    'DeclareAString_MendelssohnPianoTrio1Movement1_MIX.mp3',
#                                    'DeclareAString_MendelssohnPianoTrio1Movement2_MIX.mp3'
#                                   ])]

all_files = []
for dirpath, dirnames, filenames in files:
    for filename in filenames:
        all_files.append((filename, dirpath))
subset = sorted(random.sample(all_files, 10))

arrhythmic_songs = []
songs = []
all_beat_lengths = []
all_beat_length_counts = []

for filename, dirpath in all_files:
    basename, _ = os.path.splitext(filename)
    in_channels, samplerate = io.read_channels(os.path.join(dirpath, filename))
    in_levels = wavelets.wavedec_same(filters, n_levels, in_channels)
    in_frames = framing.levels_to_frames(in_levels)
    frame_level_energies = analysis.energy_by_frame_and_level(in_frames)
    frame_power = analysis.power_by_frame(frame_level_energies)
    beat_lengths = beats.find_length(frame_power)
    print(f'{basename}: {beat_lengths}')
    if len(beat_lengths):
        songs.append((filename, dirpath))
        all_beat_lengths.extend(beat_lengths)
        all_beat_length_counts.append(len(beat_lengths))
    else:
        arrhythmic_songs.append((filename, dirpath))

in_beat_lengths = tf.RaggedTensor.from_row_lengths(all_beat_lengths, all_beat_length_counts)

pp(in_beat_lengths)


JoelHelander_Definition_MIX: [32]
JoelHelander_ExcessiveResistancetoChange_MIX: [45]
TablaBreakbeatScience_CaptainSky_MIX: [22 33 45 55]


/mnt/custom-file-systems/efs/fs-0f02f538c5ded4757_fsap-085e69b2a4a21663d/phasic/que_onda/beats.py:34: RuntimeWarning: invalid value encountered in log
  return a * np.log(x + c) + b


MusicDelta_Reggae_MIX: [34 47]
TablaBreakbeatScience_WhoIsIt_MIX: [28 41 54]
Debussy_LenfantProdigue_MIX: [40]


2025-04-24 15:07:58.663841: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 189959792 exceeds 10% of free system memory.
2025-04-24 15:07:58.801537: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 189959792 exceeds 10% of free system memory.
2025-04-24 15:07:58.909165: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 189959952 exceeds 10% of free system memory.
2025-04-24 15:07:59.001148: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 189959872 exceeds 10% of free system memory.
2025-04-24 15:08:00.035204: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 189959872 exceeds 10% of free system memory.


TablaBreakbeatScience_Scorpio_MIX: [11 23 34 45 56]
KarimDouaidy_Hopscotch_MIX: [21 43]
MusicDelta_FunkJazz_MIX: [22 48]
MusicDelta_FusionJazz_MIX: [21 47]
TheScarletBrand_LesFleursDuMal_MIX: []
MusicDelta_InTheHalloftheMountainKing_MIX: [23 47]
ClaraBerryAndWooldog_Stella_MIX: [23 47]
LizNelson_ImComingHome_MIX: [54]
LizNelson_Coldwar_MIX: [27 39 52]
MusicDelta_Rock_MIX: [24 47]
ChrisJacoby_BoothShotLincoln_MIX: [13 27 41 54]
MusicDelta_Vivaldi_MIX: [23 47]
Creepoid_OldTree_MIX: [19 38 57]
MusicDelta_BebopJazz_MIX: [20 46]
MusicDelta_ChineseYaoZu_MIX: [13 24 47]
MusicDelta_Zeppelin_MIX: [22 36 46 58]
ClaraBerryAndWooldog_Boys_MIX: [23 45]
NightPanther_Fire_MIX: [13 20 27 41 56]
EthanHein_BluesForNofi_MIX: [49]
MusicDelta_SwingJazz_MIX: [32 47]
JoelHelander_IntheAtticBedroom_MIX: [14 41]
MusicDelta_LatinJazz_MIX: [12 22 46]
Auctioneer_OurFutureFaces_MIX: [14 31 46]
EthanHein_HarmonicaFigure_MIX: [12 25 38 49]
CelestialShore_DieForUs_MIX: [13 30 41 58]
CroqueMadame_Oil_MIX: [38]
Matthew

In [3]:
best_beat_length, closest_beat_lengths = beats.beat_match(in_beat_lengths)


(<tf.Tensor: shape=(), dtype=int32, numpy=43>,
 <tf.Tensor: shape=(182,), dtype=int32, numpy=
 array([32, 45, 45, 47, 41, 40, 45, 43, 48, 47, 47, 47, 54, 39, 47, 41, 47,
        38, 46, 47, 46, 45, 41, 49, 47, 41, 46, 46, 38, 41, 38, 15, 35, 48,
        47, 43, 43, 43, 46, 44, 38, 39, 47, 46, 44, 41, 55, 48, 49, 46, 47,
        47, 46, 36, 38, 47, 13, 37, 47, 45, 43, 41, 47, 34, 25, 30, 47, 47,
        43, 46, 41, 35, 47, 33, 50, 47, 57, 46, 47, 46, 47, 42, 47, 45, 54,
        44, 54, 37, 35, 40, 45, 45, 43, 44, 44, 39, 42, 41, 47, 51, 51, 41,
        51, 45, 34, 46, 47, 48, 34, 40, 38, 56, 44, 47, 47, 46, 42, 55, 40,
        37, 56, 48, 48, 36, 45, 39, 33, 47, 54, 52, 38, 34, 55, 54, 37, 48,
        40, 55, 46, 31, 43, 31, 43, 40, 18, 45, 35, 45, 44, 35, 41, 31, 43,
        43, 40, 45, 44, 39, 48, 47, 48, 40, 53, 39, 34, 30, 52, 53, 52, 39,
        38, 42, 37, 36, 36, 38, 44, 52, 40, 43, 33, 49], dtype=int32)>)